---
- name: Install the shell script executed by the systemd service unit
  copy:
    src: files/tune-virtio-disk-io-queues
    dest: /usr/local/bin/tune-virtio-disk-io-queues
    owner: root
    group: root
    mode: '0744'

- name: Install one shot systemd service unit
  template:
    src: systemd-startup-one-shot.service.j2
    dest: /etc/systemd/system/tune-virtio-disk-io-queues.service
    owner: root
    group: root
    mode: '0644'
  vars:
    service:
      description: Runs the tune virtio disk io queues service at system startup
      script: /usr/local/bin/tune-virtio-disk-io-queues

- name: Reread systemd configuration
  command: systemctl daemon-reload

- name: Enable the tune-virtio-disk-io-queues systemd service
  command: systemctl enable tune-virtio-disk-io-queues.service

- name: Start the tune-virtio-disk-io-queues systemd service
  command: systemctl start tune-virtio-disk-io-queues.service
