---
- name: Create plex user
  user:
    name: "{{ plex_user }}"
    home: "{{ plex_home }}"
    create_home: False
    system: True
    shell: '/usr/sbin/nologin'
  register: plex

- name: Create the plex home
  file:
    path: "{{ plex_home }}"
    owner: "{{ plex_user }}"
    group: "{{ plex_user }}"
    mode: 0755
    state: directory

- name: Add the plex repo gpg key
  copy:
    src: files/plex-keyring.gpg
    dest: /usr/share/keyrings/plex-keyring.gpg
    owner: root
    group: root
    mode: '0644'

- name: Install the plex apt list file
  template:
    src: plex.list.j2
    dest: /etc/apt/sources.list.d/plex.list
    owner: root
    group: root
    mode: '0644'

- name: Create the plex systemd override.conf dir
  file:
    path: /etc/systemd/system/plexmediaserver.service.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Install the plex systemd override.conf file
  template:
    src: plexmediaserver.service.d-override.conf.j2
    dest: /etc/systemd/system/plexmediaserver.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload the systemd daemon
  command: systemctl daemon-reload

- name: Update apt
  apt:
    update_cache: True

- name: Install plex apt packages
  apt:
    name: "{{ plex_apt_packages }}"
    state: latest
